### ISSUE TITLE
Error running training_summary example

### ISSUE THREAD

**Issue by raviolli** [CannyLab/summary_loop#1]
`python train_summary_loop.py --experiment wikinews_test --dataset_file ../data/wikinews.db`

```
Traceback (most recent call last):
  File "train_summary_loop.py", line 56, in <module>
    bert_tokenizer = utils_tokenizer.BERTCacheTokenizer()
  File "/home/tait-dev-0/summary_loop/summary_loop/utils_tokenizer.py", line 88, in __init__
    self.tokenizer.max_len = 10000
AttributeError: can't set attribute
```

`transformers              3.0.2                      py_0    conda-forge`

I created a separate conda environment. Is this a transformer version issue?

**Comment by raviolli** [comment]
Solution was to get the latest code from git.. this line of code was commented out.
