### ISSUE TITLE
cannot reshape tensor of 0 elements into shape [-1, 0] 

### ISSUE THREAD

**Issue by s103321048** [CannyLab/summary_loop#12]
I followed the instruction training model with the provided example wikinews.db:
`python train_summary_loop.py --experiment wikinews_test --dataset_file data/wikinews.db`

It did start training but later stop due to Runtimeerror:
```
Traceback (most recent call last):
  File "train_summary_loop.py", line 138, in <module>
    sampled_summaries, sampled_logprobs, sampled_tokens, input_past, sampled_end_idxs = summarizer.decode_batch(bodies, max_output_length=args.max_output_length, return_logprobs=True, sample=True)
  File "/home/robin/TrySomethingNew/summary_loop/model_generator.py", line 100, in decode_batch
    _, input_past = self.model(input_ids=inputs, past_key_values=None)
  File "/home/robin/virtual-env/summary-loop/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/robin/virtual-env/summary-loop/lib/python3.6/site-packages/transformers/modeling_gpt2.py", line 731, in forward
    return_dict=return_dict,
  File "/home/robin/virtual-env/summary-loop/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/robin/virtual-env/summary-loop/lib/python3.6/site-packages/transformers/modeling_gpt2.py", line 533, in forward
    input_ids = input_ids.view(-1, input_shape[-1])
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified
dimension size -1 can be any value and is ambiguous
```

**Comment by s103321048** [comment]
The problem is caused by the empty documents in wikinews.db

You can ignore those empty files by modifying `train_summary_loop.py` in line 127
```
bodies = [" ".join(doc.split(" ")[:300]) for doc in documents if len(doc) > 0 ] 
```

**Comment by s103321048** [comment]
That should solve the problem
